services:
  test-runner:
    image: node:20
    working_dir: /app
    env_file:
      - test-runner.env
    volumes:
      - .:/app
    networks:
      - proxy

  target-application:
    image: nginx
    volumes:
      - ./nginx.sh:/docker-entrypoint.d/nginx.sh
      - ./nginx.conf:/etc/nginx/conf.d/target-application.conf
    networks:
      - app

  browserup-proxy:
    build:
      dockerfile_inline: |
        FROM openjdk:14-alpine

        RUN wget https://github.com/browserup/browserup-proxy/releases/download/v2.0.1/browserup-proxy-2.0.1.tar
        RUN tar xvf browserup-proxy-2.0.1.tar
        RUN ln -s browserup-proxy-2.0.1 browserup-proxy

        CMD ["browserup-proxy/bin/browserup-proxy"]
    networks:
      - proxy
      - app

networks:
  proxy:
  app:
